default_context:
  project_name: 'gastos'
  project_slug: 'gastos'
  domain_main: 'gastos.com'
  domain_staging: 'prod'
  docker_swarm_stack_name_main: 'gastos-com'
  docker_swarm_stack_name_staging: 'prod'
  secret_key: '650a4a802c00dc6d6b6813f07068b77b2d1f6de5ef6a22be2469fc83f25a564c'
  first_superuser: 'root'
  first_superuser_password: 'root'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.gastos.com", "https://prod", "https://gastos.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@gastos.com'
  postgres_password: 'root'
  pgadmin_default_user: 'root'
  pgadmin_default_user_password: 'root'
  traefik_constraint_tag: 'gastos.com'
  traefik_constraint_tag_staging: 'prod'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:root'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
