"""Add column cantindad, total y fecha

Revision ID: 6cf0c15ecf77
Revises: fed05cfbf6e3
Create Date: 2021-08-26 18:37:52.504942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf0c15ecf77'
down_revision = 'fed05cfbf6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('cantidad', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('total', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('fecha', sa.Date(), nullable=True))
    op.drop_index('ix_item_description', table_name='item')
    op.drop_column('item', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_column('item', 'fecha')
    op.drop_column('item', 'total')
    op.drop_column('item', 'cantidad')
    # ### end Alembic commands ###
